name: Wait for Terraform Plan Approval
description: Uses an external service to display a plan and wait for approval/rejection. Polls in the meantime
inputs:
  command:
    description: 'What to do: either `submit` or `wait`.'
    required: true
    default: submit
  plan_contents:
    description: The contents of the plan. ANSI color codes are fine. This should be plaintext, not base64-encoded. Required when `command == submit`.
    #required: false
    #default: ''
  plan_id:
    description: The plan id to wait for. Required when `command == wait`.
    #required: false
    #default: ''
  external_service_url:
    description: Base URL for the external service that will display plans for approval
    #required: false
    default: https://terraform-plan-approval.herokuapp.com
  timeout_seconds:
    description: Give up waiting for approval/rejection after this many seconds
    #required: false
    default: 300
  polling_period_seconds:
    description: The interval (in seconds) at which we'll check the plan status
    #required: false
    default: 5

outputs:
  plan_id:
    description: When `command == submit`, returns the id of the plan generated by the external service.
  approval_prompt_url:
    description: When `command == submit`, returns the URL that a human should visit to review and approve/reject the plan.
  plan_status:
    description: 'When `command == wait`, returns the final status of the plan: either 'approved', 'rejected', or 'timed out'.'

runs:
  using: 'docker'
  image: 'Dockerfile'
